FROM alpine:latest

LABEL maintainer="chunj@mskcc.org" \
      version.samtools="1.3.1" \
      source.samtools="https://github.com/samtools/samtools/releases/tag/1.3.1"

ENV SAMTOOLS_VERSION 1.3.1

ADD https://github.com/samtools/samtools/releases/download/${SAMTOOLS_VERSION}/samtools-${SAMTOOLS_VERSION}.tar.bz2 /tmp/

RUN apk add --update --no-cache ncurses \
        && apk add --virtual=deps --update --no-cache ncurses-dev musl-dev g++ make zlib-dev \
        && cd /tmp/ && tar xjvf samtools-${SAMTOOLS_VERSION}.tar.bz2 \
        && cd /tmp/samtools-${SAMTOOLS_VERSION} && make \
        && mv /tmp/samtools-${SAMTOOLS_VERSION}/samtools /usr/bin \
        && rm -rf /var/cache/apk/* /tmp/* \
        && apk del deps

# ENTRYPOINT ["/usr/bin/samtools"]
# CMD ["--help"]
